// supervisor_data_delivery_system.h
// Auto-generated by the UltraDES notebook — DO NOT EDIT BY HAND.
// Re-run Cell 7 to regenerate.
//
// Problem   : delivery_system
// Events    : ['a1', 'a2', 'a3', 'b1', 'b2', 'b3']
// Sim seq   : ['a1', 'b1', 'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a1', 'b1', 'a2', 'b2']
// Monolithic: INCLUDED

#pragma once
#include <stdint.h>
// pgmspace.h is provided automatically by the ESP32 Arduino core.

// Total number of events across all plants and specs.
#define EVENT_COUNT 6

// Number of steps in the simulation sequence.
#define SIM_SEQ_LEN 12

// Event names in global index order (index = position in EVENT_NAMES[]).
static const char EV_0[] PROGMEM = "a1";
static const char EV_1[] PROGMEM = "a2";
static const char EV_2[] PROGMEM = "a3";
static const char EV_3[] PROGMEM = "b1";
static const char EV_4[] PROGMEM = "b2";
static const char EV_5[] PROGMEM = "b3";
static const char* const EVENT_NAMES[] PROGMEM = {
    EV_0, EV_1, EV_2, EV_3, EV_4, EV_5
};

// Simulation sequence: each entry is a global event index into EVENT_NAMES[].
static const uint16_t SIM_SEQ[] PROGMEM = {
    0, 3, 0, 3, 1, 4, 2, 5, 0, 3, 1, 4
};


// Descriptor struct — one instance per supervisor.
// All pointer fields point into PROGMEM arrays defined below.
struct SupDesc {
    const char*      name;       // supervisor label (PROGMEM string)
    uint16_t         num_states; // total number of states
    const int8_t*    init;       // one-hot initial state vector [num_states]
    const int8_t*    enable;     // enablement matrix [EVENT_COUNT * num_states]
    const uint16_t*  tcnt;       // transition pair counts per event [EVENT_COUNT]
    const int16_t*   trans;      // flat (from,to) transition pairs
};

// ── Local modular supervisors (1 total) ──────────────────────────────────
#define LMOD_COUNT 1

// S0  —  20 states, 48 transitions
static const int8_t lm0_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

static const int8_t lm0_enable[] PROGMEM = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
    0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0
};

static const uint16_t lm0_tcnt[] PROGMEM = {
    8, 6, 6, 8, 10, 10
};

static const int16_t lm0_trans[] PROGMEM = {
    0, 7, 9, 1, 10, 2, 12, 3, 13, 4, 15, 5, 16, 6, 18, 8,
    6, 1, 8, 3, 16, 9, 17, 10, 18, 12, 19, 13, 4, 1, 8, 5,
    13, 9, 14, 10, 18, 15, 19, 16, 1, 10, 2, 11, 3, 13, 4, 14,
    5, 16, 6, 17, 7, 18, 8, 19, 1, 5, 2, 6, 3, 7, 4, 8,
    9, 15, 10, 16, 11, 17, 12, 0, 13, 18, 14, 19, 1, 3, 2, 4,
    5, 7, 6, 8, 9, 12, 10, 13, 11, 14, 15, 0, 16, 18, 17, 19
};

static const char LMOD_0_NAME[] PROGMEM = "S0";

static const SupDesc LMOD_SUPS[] = {
    // S0: 20 states
    { LMOD_0_NAME, 20, lm0_init, lm0_enable, lm0_tcnt, lm0_trans },
};

// ── Local modular reduced supervisors (1 total) ──────────────────────
#define LMOD_RED_COUNT 1

// S0_red  —  3 states (-17), 14 transitions (-34)
static const int8_t lmr0_init[] PROGMEM = {
    1, 0, 0
};

static const int8_t lmr0_enable[] PROGMEM = {
    1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1
};

static const uint16_t lmr0_tcnt[] PROGMEM = {
    2, 2, 2, 2, 3, 3
};

static const int16_t lmr0_trans[] PROGMEM = {
    0, 0, 1, 1, 1, 0, 2, 1, 1, 0, 2, 1, 0, 1, 1, 2,
    0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2
};

static const char LMOD_RED_0_NAME[] PROGMEM = "S0_red";

static const SupDesc LMOD_RED_SUPS[] = {
    // S0_red: 3 states
    { LMOD_RED_0_NAME, 3, lmr0_init, lmr0_enable, lmr0_tcnt, lmr0_trans },
};

// ── Monolithic supervisor — 20 states ─────────────────────────
static const int8_t mono_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

static const int8_t mono_enable[] PROGMEM = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
    0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0
};

static const uint16_t mono_tcnt[] PROGMEM = {
    8, 6, 6, 8, 10, 10
};

static const int16_t mono_trans[] PROGMEM = {
    0, 7, 9, 1, 10, 2, 12, 3, 13, 4, 15, 5, 16, 6, 18, 8,
    6, 1, 8, 3, 16, 9, 17, 10, 18, 12, 19, 13, 4, 1, 8, 5,
    13, 9, 14, 10, 18, 15, 19, 16, 1, 10, 2, 11, 3, 13, 4, 14,
    5, 16, 6, 17, 7, 18, 8, 19, 1, 5, 2, 6, 3, 7, 4, 8,
    9, 15, 10, 16, 11, 17, 12, 0, 13, 18, 14, 19, 1, 3, 2, 4,
    5, 7, 6, 8, 9, 12, 10, 13, 11, 14, 15, 0, 16, 18, 17, 19
};

static const char MONO_NAME[] PROGMEM = "Monolithic";
#define MONO_NUM_STATES 20
static const SupDesc MONO_SUP = {
    MONO_NAME, 20, mono_init, mono_enable, mono_tcnt, mono_trans
};
#define HAS_MONO 1

